spring:
 datasource:
   url: jdbc:mysql://localhost:3306/tododetails?allowPublicKeyRetrival=true&useSSL=false
   username: root
   password: Root
 
#JPA settings
 jpa:
    hibernate:
      ddl-auto: create